osx_image: xcode9.2
language: objective-c
git:
  submodules: false
before_install: rvm use 2.3 --install --binary --fuzzy
install:
- brew install blender/homebrew-tap/rome
- bundle install --path=vendor/bundle --binstubs=vendor/bin
- bundle exec pod install --repo-update
before_script:
- rome download --platform iOS
- rome list --missing --platform ios | awk '{print $1}' | xargs carthage update --platform ios --cache-builds
script:
- xcodebuild -workspace MusicFav.xcworkspace -scheme MusicFav -sdk iphonesimulator11.2 CODE_SIGNING_REQUIRED=NO
cache:
  directories:
  - vendor/bundle
  - Pods
env:
  global:
  - secure: KPEZUpl1e9BTyAPPri6qFNJuMMXr3FVs5P7HuZuyh0hIzJ5N9WUJkUN+O7u73BnXHO4DLaFvhx0eRG4ggRn73M3N2WrQSdthEilMJtF5MJGB6UGW5Cy1WcBqYwCqpflevqLTS2EWhyHW9YrGuGGh4gzAxZphxdkA3fE/WcD+Kos=
