osx_image: xcode9
language: objective-c
before_install: rvm use 2.3 --install --binary --fuzzy
install: bundle install --without=documentation
before_script:
    - brew update
    - brew install carthage || true
    - travis_wait 60 sh carthage_build.sh
    - pod install
script: xcodebuild -workspace MusicFav.xcworkspace -scheme MusicFav
cache:
  directories:
  - Pods
  - Carthage
