osx_image: xcode9
language: objective-c
git:
  submodules: false
before_install: rvm use 2.3 --install --binary --fuzzy
install: bundle install --without=documentation
before_script:
    - travis_wait 60 sh carthage_checkout.sh
    - travis_wait 60 bash -x carthage_build.sh
    - pod install
script: xcodebuild -workspace MusicFav.xcworkspace -scheme MusicFav -sdk iphonesimulator11.0 CODE_SIGNING_REQUIRED=NO
cache:
  bundler: true
  cocoapods: true
  directories:
  - Carthage
