osx_image: xcode9
language: objective-c
git:
  submodules: false
before_install: rvm use 2.3 --install --binary --fuzzy
install:
  - bundle install --path=vendor/bundle --binstubs=vendor/bin
  - bundle exec pod install
  - bash -x carthage_checkout.sh
before_script:
  - travis_wait 60 carthage build --cache-builds --platform iOS
script: xcodebuild -workspace MusicFav.xcworkspace -scheme MusicFav -sdk iphonesimulator11.0 CODE_SIGNING_REQUIRED=NO
cache:
  directories:
    - vendor/bundle
    - Pods
    - Carthage
