platform :ios, '7.0'
pod 'NXOAuth2Client', '~> 1.2.2'
pod 'AFNetworking',   '~> 2.0'
pod 'JASidePanels',   '~> 1.3'
pod 'SDWebImage',     '~> 3.6'
pod 'XCDYouTubeKit',  '~> 2.0.3'
pod 'RATreeView',     :git => "https://github.com/kumabook/RATreeView.git", :branch => 'pull_to_refresh'
pod 'MBProgressHUD',  '~> 0.8'
