platform :ios, '8.0'
use_frameworks!
pod 'NXOAuth2Client',       '>= 1.2.2'
pod 'AFNetworking',         '>= 2.0'
pod 'JASidePanels',         '>= 1.3'
pod 'SDWebImage',           '>= 3.6'
pod 'XCDYouTubeKit',        '>= 2.1.1'
pod 'RATreeView',           :git => "https://github.com/kumabook/RATreeView.git", :branch => 'pull_to_refresh'
pod 'MBProgressHUD',        '>= 0.8'
pod 'MCSwipeTableViewCell', '>= 2.1.0'
pod 'Snap',                 '>= 0.0.6'
